//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.DBContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MABRUKLISTEntities : DbContext
    {
        public MABRUKLISTEntities()
            : base("name=MABRUKLISTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<mblist_address> mblist_address { get; set; }
        public virtual DbSet<mblist_category> mblist_category { get; set; }
        public virtual DbSet<mblist_group> mblist_group { get; set; }
        public virtual DbSet<mblist_neighborhoods> mblist_neighborhoods { get; set; }
        public virtual DbSet<mblist_title> mblist_title { get; set; }
        public virtual DbSet<mblist_type> mblist_type { get; set; }
    }
}
