//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class mblist_events_detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mblist_events_detail()
        {
            this.mblist_events_detail1 = new HashSet<mblist_events_detail>();
        }
    
        public int event_detail_key { get; set; }
        public int event_detail_category_key { get; set; }
        public int event_detail_type_key { get; set; }
        public string event_detail_title { get; set; }
        public System.DateTime event_detail_date { get; set; }
        public string event_detail_address { get; set; }
        public string event_detail_discription { get; set; }
        public string event_detail_user_key { get; set; }
        public Nullable<int> event_parent { get; set; }
        public string event_template_path { get; set; }
        public string event_subject { get; set; }
        public string event_subject_color { get; set; }
        public string event_font_color { get; set; }
    
        public virtual mblist_category mblist_category { get; set; }
        public virtual mblist_type mblist_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mblist_events_detail> mblist_events_detail1 { get; set; }
        public virtual mblist_events_detail mblist_events_detail2 { get; set; }
    }
}
