//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class mblist_event_guests
    {
        public int guest_key { get; set; }
        public int guest_event_key { get; set; }
        public string guest_user_key { get; set; }
    
        public virtual mblist_events_detail mblist_events_detail { get; set; }
    }
}
