//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class mblist_user_info
    {
        public int usr_key { get; set; }
        public string usr_first_name { get; set; }
        public string usr_last_name { get; set; }
        public string usr_cell_phone { get; set; }
        public string usr_foreign { get; set; }
        public Nullable<int> usr_title_key { get; set; }
        public Nullable<int> usr_group_key { get; set; }
        public Nullable<int> usr_sub_title { get; set; }
        public string usr_observation { get; set; }
        public Nullable<int> usr_neighbourhood_key { get; set; }
        public Nullable<int> usr_congregation_key { get; set; }
        public string usr_children { get; set; }
        public Nullable<int> usr_address { get; set; }
        public string usr_sur_name { get; set; }
        public string usr_apartment { get; set; }
        public string usr_blood { get; set; }
        public string usr_company { get; set; }
        public string usr_phone { get; set; }
        public string usr_relationship { get; set; }
        public bool usr_donar { get; set; }
        public string usr_image_path { get; set; }
        public string usr_aspnet_user { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual mblist_address mblist_address { get; set; }
        public virtual mblist_congregation mblist_congregation { get; set; }
        public virtual mblist_group mblist_group { get; set; }
        public virtual mblist_neighborhoods mblist_neighborhoods { get; set; }
        public virtual mblist_subtitle mblist_subtitle { get; set; }
        public virtual mblist_title mblist_title { get; set; }
    }
}
