//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class mblis_events
    {
        public int event_key { get; set; }
        public Nullable<int> event_category_key { get; set; }
        public Nullable<int> event_type_key { get; set; }
        public string event_title { get; set; }
        public string event_date { get; set; }
        public string event_address { get; set; }
        public string event_discription { get; set; }
    }
}
