//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class mblist_chooseEvent
    {
        public int choose_key { get; set; }
        public Nullable<int> chooseGroup_key { get; set; }
        public Nullable<int> chooseCongregation_key { get; set; }
        public Nullable<int> chooseNeighbourhood_key { get; set; }
    }
}
